# Backpropagation Using Regression Simple Intuition

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [4]:
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [ ]:
#layer_dims = [2(input_neuron), 2(hidden_neuron), 1(output_neuron)]  - List containing the number of neurons in each layer
def initialize_parameters(layer_dims):
  np.random.seed(3)    # Every run gives same weights → easier debugging, Fixes randomness so results are reproducible
  parameters = {}      # Empty dictionary to store: [[W1, b1] ,[W2, b2]]
  L = len(layer_dims)  # Number of layers (including input layer) L = 3

  for l in range(1,L): # Why start from 1? -> Layer 0 is input layer → no weights, We creates weight between layer1 and layer0
    # Creates keys: W1, W2, np.ones((rows, cols)) and matrix of 1's, np.ones(neurons in previous layer, neurons in current layer)
    parameters['W'+str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1  # Why 0.1 -> Prevents large activations, weight scaling
    parameters['b'+str(l)] = np.zeros((layer_dims[l],1))  # Bias is added to each neuron, Shape: (neurons_in_layer, 1)
  return parameters

In [ ]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
# If First layer, A_prev = input features X and  If Hidden layer, A_prev = output of previous activation
def linear_forward(A_prev, W, b):
  Z = np.dot(W.T, A_prev) + b
  return Z  # Z is not the final output, just the linear part.

In [ ]:
#Forward Propagation -> data flows from input → hidden → output
def L_layer_forward(X, parameters): # X-input data (features), parameters-List containing all weights and biases
  A = X
  L = len(parameters) // 2     # Parameters [[W1,b1],[W2,b2]] which means 4//2 = 2

  for l in range(1, L+1):  # Iterates layer by layer, Forward Propagation always uses A(l) = f( W(l)ᵀ.A(l−1)) + b(l)
    A_prev = A             # save the previous layer’s output  initially A_prev = A0 = X
    W1 = parameters['W' + str(l)]  # Fetches the weight matrix for layer l
    b1 = parameters['b' + str(l)]  # Fetches bias vector for layer l
    # print("A" + str(l-1) + " : ", A_prev)
    # print("W" + str(l) + " : ", W1)  # weights of the current layer
    # print("b" + str(l) + " : ", b1)  # bias vector for the current layer
    # print("--"*20)   # Makes output readable when many layers are printed

    A = linear_forward(A_prev, W1, b1)
    # print("A" + str(l) + " : ", A) # Output of current layer
    # print("**"*20)  # readability

  return A, A_prev   # A output of the current network, A_prev previous layer’s activation

In [ ]:
# # change for student X=values[i] and y=values[i][0] change the value of i according to (0)1st,(1)2nd,(3rd)2,(4th)3 student
# X = df[['cgpa','profile_score']].values[0].reshape(2,1) # shape (no. of features, no. of training sample)
# y = df[['lpa']].values[0][0]

# #Parameter initialization
# parameters = initialize_parameters([2,2,1])
# print('parameters', parameters)
# print('X : ', X)
# print('y :', y)

In [ ]:
# y_hat, A1 = L_layer_forward(X, parameters)

In [ ]:
# y_hat = float(y_hat[0][0])
# print(y_hat)
# print(A1)

In [ ]:
def update_parameters(parameters,y,y_hat,A1,X):
  # Output Layer
  parameters['W2'][0][0] += (0.001 * 2 * (y-y_hat)*A1[0][0]) # Output of hidden neuron A11 -> O11
  parameters['W2'][1][0] += (0.001 * 2 * (y-y_hat)*A1[1][0]) # Output of hidden neuron A12 -> O12
  parameters['b2'][0][0] += (0.001 * 2 * (y-y_hat))

  # Hidden Layer
  parameters['W1'][0][0] += (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] += (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] += (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] += (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] += (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] += (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0])

In [ ]:
# update_parameters(parameters, y, y_hat, A1, X)

In [ ]:
# parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

In [ ]:
#epochs implementation
parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):
    X = df[['cgpa','profile_score']].values[j].reshape(2,1) #shape(no. of features, no. of training samples)
    y = df[['lpa']].values[j][0]

    #parameter initialization
    y_hat, A1 = L_layer_forward(X, parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters, y, y_hat, A1, X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())
parameters

Epoch -  1 Loss -  26.28249792398698
Epoch -  2 Loss -  19.438253848220803
Epoch -  3 Loss -  10.139874435827522
Epoch -  4 Loss -  3.385561305106485
Epoch -  5 Loss -  1.3198454128484565

{'W1': array([[0.273603  , 0.3993222 ],
        [0.28787155, 0.42586102]]),
 'b1': array([[0.02885522],
        [0.03133223]]),
 'W2': array([[0.42574893],
        [0.50219328]]),
 'b2': array([[0.11841278]])}

#Backpropagation Regression Intuition Using Keras

In [ ]:
import numpy as np
import pandas as pd
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2)) # 2 Input Neurons and 2 Hidden Neurons
model.add(Dense(1,activation='linear')) #Output Neuron

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()  # 2*2(w)+2(b)=6, 2(w)+1(b)=3

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#weights that model is taking randomly
model.get_weights()

[array([[-0.5284841 ,  0.36269677],
        [ 0.21972036,  0.3278253 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.3317399],
        [ 1.0378925]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
#Updates weights according to my intuition
new_weights = [
    np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
    np.array([0.,0.],dtype=np.float32),
    np.array([[0.1],[0.1]],dtype=np.float32),
    np.array([0.],dtype=np.float32)
]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [ ]:
X_train = df[['cgpa','profile_score']].values.astype(np.float32)
y_train = df['lpa'].values.astype(np.float32)
print(y_train.ndim)
print(X_train.shape[1])

1
2

In [ ]:
model.fit(X_train, y_train, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 27.4954
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 27.1396
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21.3267
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 22.6719
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 26.1736
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25.8441
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24.6811
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 29.1901
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 31.0423
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 28.3198
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 18.6997
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 26.7929
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 29.1540
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 20.3130
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21.4387
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 19.8692
Epoch 17/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 21.8387
Epoch 18/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 18.9655
Epoch 19/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23.9321
Epoch 20/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 23.3872
Epoch 21/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 14.6798
Epoch 22/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 16.2179
Epoch 23/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.4576
Epoch 24/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.2122
Epoch 25/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12.9392
Epoch 26/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 18.2970
Epoch 27/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12.6418
Epoch 28/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 19.8528
Epoch 29/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 18.3517
Epoch 30/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 17.7658
Epoch 31/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12.8900
Epoch 32/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.0998
Epoch 33/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 15.9988
Epoch 34/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 15.0412
Epoch 35/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.2472
Epoch 36/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.5797
Epoch 37/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.7782
Epoch 38/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 11.2359
Epoch 39/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 11.2799
Epoch 40/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12.1694
Epoch 41/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.6804
Epoch 42/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.3256
Epoch 43/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.9724
Epoch 44/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.9090
Epoch 45/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.3942
Epoch 46/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5732
Epoch 47/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.5033
Epoch 48/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4003
Epoch 49/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.8910
Epoch 50/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.5063
Epoch 51/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.1942
Epoch 52/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.3500
Epoch 53/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.4197
Epoch 54/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.3138
Epoch 55/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.8192
Epoch 56/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.5377
Epoch 57/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.1604
Epoch 58/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.9668
Epoch 59/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.4939
Epoch 60/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.2569
Epoch 61/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.2291
Epoch 62/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.7294
Epoch 63/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0864
Epoch 64/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.7590
Epoch 65/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0420
Epoch 66/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.2852
Epoch 67/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.7563
Epoch 68/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.7605
Epoch 69/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.2507
Epoch 70/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.5687
Epoch 71/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.4651
Epoch 72/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.5775
Epoch 73/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.9901
Epoch 74/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8367
Epoch 75/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.4196

In [ ]:
model.get_weights()

[array([[0.37368   , 0.37368   ],
        [0.36571115, 0.36571115]], dtype=float32),
 array([0.27239478, 0.27239478], dtype=float32),
 array([[0.3730008],
        [0.3730008]], dtype=float32),
 array([0.20486452], dtype=float32)]